### ISSUE TITLE
Fatal Python error: new_threadstate called from within parallel context

### ISSUE THREAD

**Issue by retsyo** [pyparallel/pyparallel#7]
I am using the downloaded `pyparallel-3.3.99805.amd64` on win7. however
```
D:\pyparallel-3.3.99805.amd64\examples\pydata>..\..\python.exe -m test
== CPython 3.3.5 (3.3.5.99805-0:g96c3879+, Nov 11 2015, 17:15:16) [MSC v.1600 64 bit (AMD64)]
==   Windows-7-6.1.7601-SP1 little-endian
==   D:\pyparallel-3.3.99805.amd64\build\test_python_81208
Testing with flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0,
bytes_warning=0, quiet=0, hash_randomization=1)
[  8/378] test_doctest
Warning -- logging._handlerList was modified by test_doctest
[ 11/378] test___all__
Warning -- os.environ was modified by test___all__
[ 19/378] test_array
test test_array failed -- multiple errors occurred; run in verbose mode for details
[ 21/378/1] test_async
test test_async crashed -- Traceback (most recent call last):
  File "D:\pyparallel-3.3.99805.amd64\lib\test\regrtest.py", line 1214, in runtest_inner
    the_package = __import__(abstest, globals(), locals(), [])
  File "D:\pyparallel-3.3.99805.amd64\lib\test\test_async.py", line 36, in <module>
    SERVICES_IP = socket.getaddrinfo(*ECHO_HOST)[0][4][0]
socket.gaierror: [Errno 11001] getaddrinfo failed

[ 27/378/2] test_base64
test test_base64 failed -- multiple errors occurred; run in verbose mode for details
[ 42/378/3] test_capi
Fatal Python error: new_threadstate called from within parallel context (..\Python\pystate.c:176)

Caught exception, wrote dump file to pyparallel.dmp.
`set PYPARALLEL_NO_MINIDUMP=1` to disable this functionality
(useful if you want to attach Visual Studio to debug).
```

**Comment by tpn** [comment]
Eek, only took me ~2.1 ish years to see this issue.  But, long story short, yeah, the Python test suite doesn't work with PyParallel.
